[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "William Warwick", email = "warwickw8@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "google-api-python-client>=2.200.0",
    "google-auth-oauthlib>=1.4.1",
    "google-genai>=2.22.0",
    "pillow>=12.3.0",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "uvicorn>=0.52.4",
]

[project.scripts]
backend = "backend:main"

[tool.vercel]
entrypoint = "src.backend.main:app"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
